### PR TITLE
[Memory-opti:runtime allocations] Fix ur-ghast armor renderer spamming allocations

### LINKED ISSUE #22959: memory leak when wearing animated twilight forest trophy
### Your GTNH Discord Username

sunorcio

### Your Pack Version

2.8.3

### Your Server

private server

### Java Version

Java 25

### Type of Server

Vanilla Forge

### Your Expectation

simply equipping an item

### The Reality

memory appears to leak when rendering the animated equipable twilight forest boss "ur-ghast" trophy mask. when putting it on, another player started experiencing freezes after a while playing (around 1 hour tops) due to memory filling up, both reported in-game and task manager, going up past the allocated maximum. I experienced the same but it took much longer, i suspect its because i only render the mask when looking at my inventory.

issues are gone after unequipping it. whe tried a lot of fixes before coming to this conclusion, so we know the issue happens in java 25 both normal and graalvm-ce, java 21, both 2.8.1 and 2.8.3 gtnh versions and both windows 10 and 11 (linux seems unaffected but not sure).

### Your Proposal

idk this puzzled us for a couple days and made the game unplayable

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by Alexdoru**
Fixes : https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/22959

### CODE REVIEW

File: src/main/java/twilightforest/client/TFClientProxy.java [hunk 1]
```diff
@@ -235,267 +236,100 @@ public void doOnLoadRegistration() {
...
         // animated textures
-        // TextureFXManager.instance().addAnimation(new TextureTFMagicLeavesFX(mc, BlockTFMagicLeaves.SPR_TIMELEAVES,
-        // BlockTFMagicLeaves.SPR_TIMEFX));
-        // TextureFXManager.instance().addAnimation(new TextureTFMagicLeavesFX(mc, BlockTFMagicLeaves.SPR_TRANSLEAVES,
-        // BlockTFMagicLeaves.SPR_TRANSFX));
-        // TextureFXManager.instance().addAnimation(new TextureTFMagicLeavesFX(mc, BlockTFMagicLeaves.SPR_SORTLEAVES,
-        // BlockTFMagicLeaves.SPR_SORTFX));
+        // TextureFXManager.instance().addAnimation(new TextureTFMagicLeavesFX(mc, BlockTFMagicLeaves.SPR_TIMELEAVES, BlockTFMagicLeaves.SPR_TIMEFX));
+        // TextureFXManager.instance().addAnimation(new TextureTFMagicLeavesFX(mc, BlockTFMagicLeaves.SPR_TRANSLEAVES, BlockTFMagicLeaves.SPR_TRANSFX));
+        // TextureFXManager.instance().addAnimation(new TextureTFMagicLeavesFX(mc, BlockTFMagicLeaves.SPR_SORTLEAVES, BlockTFMagicLeaves.SPR_SORTFX));
```
Comment (boubou19) [inline src/main/java/twilightforest/client/TFClientProxy.java:332]: Dead code

File: src/main/java/twilightforest/client/model/ModelTFTrophyArmor.java [hunk 2]
```diff
@@ -121,12 +122,9 @@ public void render(Entity par1Entity, float par2, float par3, float par4, float
                 dZ = 0.0f;
             }
             case 3 -> { // Ur-Ghast
-                bipedHead = new ModelRenderer(this, 0, 0);
-                ModelTFTowerBoss urGhastModel = new ModelTFTowerBoss();
                 urGhastModel.body.offsetY = -1f;
-                urGhastModel.setRotationAngles(0.0F, 0, time, 0, 0.0F, 0.0625F, par1Entity);
+                urGhastModel.setRotationAngles(0.0F, 0, time, 0, 0.0F, 0.0625F, entity);
                 time++;
-                bipedHead.addChild(urGhastModel.body);
```
Comment (boubou19) [inline src/main/java/twilightforest/client/model/ModelTFTrophyArmor.java:129]: does this removal cause any side effect?

Comment (Alexdoru) [reply src/main/java/twilightforest/client/model/ModelTFTrophyArmor.java:129]: I don't think so it's already added in the constructor

File: src/main/java/twilightforest/client/TFClientProxy.java (hunk 1 above)
Comment (Alexdoru) [reply src/main/java/twilightforest/client/TFClientProxy.java:332]: my pr just removes spotless, doesn't delete dead code

**Review by boubou19 — APPROVED** [review]
