### PR TITLE
Fix unlocalized names for various leaves and logs

### LINKED ISSUE #105: Raw locale key on tile.TFLog.12.name
### Your GTNH Discord Username

_No response_

### Mod Version

2.7.5

### Bug Report

WAILA shows tile.TFLog.12.name on some of the Twilight Oak Woods
the lang file only covers 0, 4 and 8 but not 12, causing this problem.

### Java Version

Java 21

### Mod List or GTNH Pack Version

not related

### Final Checklist

- [x] I have searched the issues and haven't found a similar issue.

### LINKED ISSUE #124: Some blocks have unlocalized names
### Your GTNH Discord Username

_No response_

### Mod Version

2.7.12

### Bug Report

Some of the canopy leaves and logs, there seems to be at least two variants of each. Some have the proper names, others do not. (Ignore the textures, I have a resource pack) I will add any other blocks I find to this.

Image
Image

### Java Version

Java 21

### Mod List or GTNH Pack Version

Twilight Forest should be all that's needed.

### Final Checklist

- [x] I have searched the issues and haven't found a similar issue.

### PR DESCRIPTION
**Pull request by tiffit**
Fixes logs and leaves showing their un-localized name in WAILA. Also simplified the translation files by removing a lot of duplicates.

Closes https://github.com/GTNewHorizons/twilightforest/issues/124
Closes https://github.com/GTNewHorizons/twilightforest/issues/105

### CODE REVIEW

File: src/main/java/twilightforest/item/ItemBlockTFLog.java [hunk 1]
```diff
@@ -1,58 +1,19 @@
...
-
-public class ItemBlockTFLog extends ItemBlock {
-
-    public static final String[] woodNames = { "oak", "canopy", "mangrove", "darkwood", "x", "root", "oreroot",
-            "rotten" };
+public class ItemBlockTFLog extends ItemBlockTFMeta {
 
     public ItemBlockTFLog(Block log) {
         super(log);
         setHasSubtypes(true);
```
Comment (Luca-Guettinger) [inline src/main/java/twilightforest/item/ItemBlockTFLog.java]: setHasSubtypes(true) and setMaxDamage(0) are already called in the ItemBlockTFMeta constructor. Same for ItemBlockTFLeaves.

File: src/main/java/twilightforest/item/ItemBlockTFLeaves.java [hunk 2]
```diff
@@ -1,36 +1,19 @@
...
-    /**
-     * Gets an icon index based on an item's damage value
-     */
-    @Override
-    public IIcon getIconFromDamage(int par1) {
-        return TFBlocks.leaves.getIcon(2, par1);
-    }
-
     @Override
     public String getUnlocalizedName(ItemStack itemstack) {
```
Comment (Luca-Guettinger) [inline src/main/java/twilightforest/item/ItemBlockTFLeaves.java]: Identical override to ItemBlockTFLog. Could use a single class, but separate ones are fine if these might diverge later.

**Review by Luca-Guettinger — COMMENTED** [review]
Looks good. 2 small nits, nothing blocking.

File: src/main/java/twilightforest/item/ItemBlockTFLeaves.java (hunk 2 above)
Comment (tiffit) [reply src/main/java/twilightforest/item/ItemBlockTFLeaves.java]: Created a single "ItemBlockTFTree" class that both log and leaf itemblocks use now. Also fixed the other nit in this class.

**Review by Luca-Guettinger — APPROVED** [review]
